// <auto-generated />
namespace Final_Project_APWDN_SMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changegradetable_again : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changegradetable_again));
        
        string IMigrationMetadata.Id
        {
            get { return "202009181752004_change grade table_again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
