// <auto-generated />
namespace Final_Project_APWDN_SMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateteachertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateteachertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202009201528190_update teacher table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
